
name = "LoDashReactComponents"
uuid = "1b08a953-4be3-4667-9a23-8f17f5d62503"
authors = ["Piotr Mitros <pmitros@ets.org>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
