xmpp:
  sink: # Receives messages. We'll need many of these.
    jid: sink@localhost
    password: {{RANDOM1}}
  source: # Sends messages.
    jid: source@localhost
    password: {{RANDOM1}}
  stream: # For debugging
    jid: stream@localhost
    password: {{RANDOM1}}
auth:
  password-file: passwd.lo
pubsub:
    type: redis
kvs:
    type: redis
roster-data:
    source: all
aio:
    session_secret: {{RANDOM2}}
    session_max_age: 3600
config:
    run_mode: dev
    debug: []
theme:
    server-name: Learning Observer
    front-page-pitch: Learning Observer is an experimental dashboard. If you'd like to be part of the experiment, please contact us. If you're already part of the experiment, log in!
    logo-big: /static/media/logo-clean.jpg
event_auth:
    local_storage:
        userfile: students.yaml
        allow_guest: true